shim-pyoo/ShimPyo-FE

entities/MedicineTimeSettingComponent/ui/ChangeTimeButton.jsx
entities/MedicineTimeSettingComponent/ui/EatingTimeButton.jsx
entities/MedicineTimeSettingComponent/ui/MealButton.jsx
entities/MedicineTimeSettingComponent/ui/MedicineText.jsx
entities/MedicineTimeSettingComponent/ui/Toolbar.jsx
pages/MedicineTimeSetting.jsx

- close #4 
<br>
약 복용 메인페이지 스타일 완성(추후 수정 예정)
<br>
<br>

약 복용 메인페이지 스타일 완성(추후 수정 예정)

---

entities/ChangeMedicineComponent/ui/WhenMedicineText.jsx
pages/MedicineComplete.jsx

- close #13
<br>
약 복용 수정 완료 페이지를 제작하였습니다.
<br>
<br>

약 복용 수정 완료 페이지 제작

---

App.js
app.json
entities/BreathMeasure/ui/AudioRecord.jsx
entities/BreathMeasure/ui/PlayAudio.jsx
entities/main/ui/MeasureBreathButton.jsx
package-lock.json
package.json
pages/BreathMeasure.jsx
yarn.lock

- close #18 
<br>
- expo-av 라이브러리를 이용하여 IOS로 음성 녹음 및 재생 기능 구현 
<br>
<br>
- 야호 ~~~~

✨ 마이크로 녹음 및 재생 기능 구현

---

App.js
assets/images/circle.svg
entities/BreathMeasure/ui/BreathNow.jsx
package-lock.json
package.json
yarn.lock

- close #25 
<br>
- 오늘의 쉼 탭 circle progress bar 추가
- 아이콘 클릭 시 progress가 증가되도록 구현
<br>
<br>

✨ 오늘의쉼 탭 circle progress bar 추가

---

App.js

- close #37 
<br>
- App.js에 TodaysShim.js 추가
<br>
<br>

🐛 App.js에 TodaysShim.js 추가

---

entities/TodaysShim/ui/BreathNow.jsx
entities/TodaysShim/ui/Result.jsx
pages/TodaysShim.jsx

- close #30 
<br>
- 측정 버튼 클릭 시 녹음
- 녹음된 파일을 배열에 넣어서 관리하도록 구현함 (총 3개의 녹음 파일 존재)
<br>
<br>

✨ 오늘의 쉼 - 측정 버튼 클릭 시 녹음 기능 구현

---

entities/MedicineTimeSettingComponent/ui/EatingTimeButton.jsx
entities/MedicineTimeSettingComponent/ui/MealButton.jsx

- close #6 
<br>
더미데이터를 이용하여 현재 약 복용 알림 시간 페이지를 수정하였습니다. 
<br>
<br>

약 복용 알림 시간 페이지 수정

---

App.js

- close #45 
<br>
- appjs에 네비게이션 추가
- app.js  코드 구조 수정 
<br>
<br>

🐛 App.js 구조 수정

---

App.js
entities/ChattingRoom/AiChat.jsx
entities/ChattingRoom/ChattingContent.jsx
entities/ChattingRoom/DefaultChat.jsx
entities/ChattingRoom/Input.jsx
entities/ChattingRoom/TitleBar.jsx
entities/SumAiChat/ui/FloatingButton.jsx
pages/ChattingRoom.jsx

- close #66
<br>
챗봇 디폴트 질문을 누르면 대답을 하는 것을 구성하였습니다.
<br>
<br>

챗봇 디폴트 질문 구성

---

App.js
pages/Main.jsx
pages/SumHistory.jsx
shared/component/NavigationBar.jsx

- close #63 
<br>
- 네비게이션 바 구조 수정 
<br>
<br>

🎨 네비게이션 코드 구조 수정

---

entities/HospitalTimeSettingComponent/api/HospitalApi.js
entities/HospitalTimeSettingComponent/ui/Calendar.jsx
entities/HospitalTimeSettingComponent/ui/HospitalReservationTimeModal.jsx
entities/HospitalTimeSettingComponent/ui/HospitalSearchModal.jsx
entities/HospitalTimeSettingComponent/ui/TimePicker.jsx
entities/main/api/MainApi.js
entities/main/ui/SettingComponent.jsx
entities/main/ui/SettingComponentSection.jsx
pages/HospitalTimeSetting.jsx

- close #72 
<br>
- 병원 검색 API 통신
- 병원 방문 일정 API 통신
- 병원 방문 일정 조회 API 통신
- 병원 방문 남은 시간 조회 API 통신
<br>
<br>

👽 병원 방문 설정 관련 API 통신

---

entities/SumHistory/ComparedLastWeek.jsx
entities/SumHistory/Contents.jsx
entities/SumHistory/PefAvg.jsx
entities/SumHistory/ThisWeekShimStatus.jsx

- close #69 
<br>
- 주간 평균 최대 호기량 그래프
- 지난 주 대비 최대 호기량 수치
<br>
<br>

✨ 주간 평균 그래프 , 지난주 대비 호기량 레이아웃만 구현

---

entities/ChattingRoom/ChattingContent.jsx
entities/ChattingRoom/DefaultChat.jsx
entities/ChattingRoom/Input.jsx
entities/ChattingRoom/TitleBar.jsx
pages/ChattingRoom.jsx

- close #79
<br>
움직이는 인풋창 구현 및 채팅창을 구현하였습니다.
<br>
<br>

움직이는 인풋창 구현 및 채팅창 구현

---

entities/MyPage/api/MyPageApi.js
entities/MyPage/ui/PEFInfo.jsx

- close #이슈번호
<br>
- 간단하게 한 줄로 작성하면 됩니다. (ex. 메인 페이지의 캘린더를 구현했습니다.)
<br>
<br>

👽️ 나의 기준 최대호기량 조회 비동기처리

---

entities/MyPage/api/MyPageApi.js
entities/MyPage/model/model.js
entities/MyPage/ui/PEFInfo.jsx
entities/SumHistory/api/SumHistory.js
entities/SumHistory/ui/Selecter.jsx
entities/SumHistory/ui/ThisMonthShimStatus.jsx
entities/SumHistory/ui/ThisWeekShimStatus.jsx
entities/TodaysShim/ui/BreathNow.jsx
entities/main/ui/MeasureBreathButton.jsx

- close #94 
<br>
- 이번 달 쉼 상태 조회 API 통신 
- 이번 주 쉼 상태 조회 API 통심
<br>
<br>

👽️ 숨지표 숨상태 조회 API 통신

---

App.js
entities/ChattingRoom/api/ChattingRoomAPi.js
entities/ChattingRoom/ui/TitleBar.jsx
pages/ChattingRoom.jsx
pages/SumAiChat.jsx

- close #100 
<br>
- 채팅방 이름 수정 API 통신
- 화면 전환 애니메이션 없앰 
<br>
<br>

👽️ 채팅방 이름 수정 API 통신

---

pages/SumAiChat.jsx

- close 
<br>
- 채팅방 새로고침 기능 추가 
<br>
<br>

⚡️ 채팅방 새로고침 기능 추가

---

App.js
entities/ChattingRoom/ui/AiChat.jsx
entities/ChattingRoom/ui/ChattingContent.jsx
entities/ChattingRoom/ui/DefaultChat.jsx
entities/ChattingRoom/ui/Loading.jsx
entities/ChattingRoom/ui/MyChat.jsx
entities/ChattingRoom/ui/TitleBar.jsx
entities/SumHistory/ui/ComparedLastWeek.jsx
entities/SumHistory/ui/ThisMonthShimStatus.jsx
entities/SumHistory/ui/ThisWeekShimStatus.jsx
entities/main/ui/MeasureBreathButton.jsx
pages/Main.jsx
pages/SumAiChat.jsx

- close #102 
<br>
- 디폴트 채팅
- 로딩중
<br>
<br>

⚡️ 디폴트 채팅 및 로딩중 애니메이션 구현

---

entities/ChattingRoom/ui/ChattingContent.jsx
entities/ChattingRoom/ui/DefaultChat.jsx
entities/ChattingRoom/ui/Input.jsx
entities/SumHistory/ui/ComparedLastMonth.jsx
entities/SumHistory/ui/ComparedLastWeek.jsx
entities/SumHistory/ui/ThisMonthShimStatus.jsx
entities/SumHistory/ui/ThisWeekShimStatus.jsx
entities/TodaysShim/ui/History.jsx
entities/TodaysShim/ui/Result.jsx
entities/WhenBreakfast/ui/BreakfastTimePicker.jsx
entities/WhenDinner/ui/DinnerTimePicker.jsx
entities/WhenLunch/ui/LunchTimePicker.jsx
pages/ChattingRoom.jsx

- close #이슈번호
<br>
- 간단하게 한 줄로 작성하면 됩니다. (ex. 메인 페이지의 캘린더를 구현했습니다.)
<br>
<br>

🎨 자잘자잘한거 수정 

---

App.js
entities/SumHistory/ui/MonthlyPefAvg.jsx
entities/SumHistory/ui/PefAvg.jsx
entities/SumHistory/ui/ThisWeekShimStatus.jsx
entities/TodaysShim/ui/BreathNow.jsx
entities/TodaysShim/ui/Graph.jsx
entities/TodaysShim/ui/History.jsx
entities/main/ui/MeasureBreathButton.jsx

- close #이슈번호
<br>
- 간단하게 한 줄로 작성하면 됩니다. (ex. 메인 페이지의 캘린더를 구현했습니다.)
<br>
<br>

🎨 최종 코드 수정
